### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by Aflah2635** [Lukeos11/MC-Server-Status-Bot#2]
throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Unknown Message
    at RequestHandler.execute (D:\bots\MC-Server-Status-Bot-1.0.1\node_modules\discord.js\src\rest\RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (D:\bots\MC-Server-Status-Bot-1.0.1\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async MessageManager._fetchId (D:\bots\MC-Server-Status-Bot-1.0.1\node_modules\discord.js\src\managers\MessageManager.js:214:18) {
  method: 'get',
  path: '/channels/922765565666410527/messages/922776394218475550',
  code: 10008,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
}

**Comment by Aflah2635** [comment]
> throw new DiscordAPIError(data, res.status, request); ^
> 
> DiscordAPIError: Unknown Message at RequestHandler.execute (D:\bots\MC-Server-Status-Bot-1.0.1\node_modules\discord.js\src\rest\RequestHandler.js:298:13) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async RequestHandler.push (D:\bots\MC-Server-Status-Bot-1.0.1\node_modules\discord.js\src\rest\RequestHandler.js:50:14) at async MessageManager._fetchId (D:\bots\MC-Server-Status-Bot-1.0.1\node_modules\discord.js\src\managers\MessageManager.js:214:18) { method: 'get', path: '/channels/922765565666410527/messages/922776394218475550', code: 10008, httpStatus: 404, requestData: { json: undefined, files: [] } }
